---
dist: focal

language: python
python:
  - "3.8"

branches:
  only:
    - master
    - dev
    - galaxy

before_install:
  - sudo apt-get update
  - sudo apt-get install -y tox make latexmk texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-xetex

script:
  - tox
